// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akffppqsrwveplnbeisx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrZmZwcHFzcnd2ZXBsbmJlaXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjE4MzIsImV4cCI6MjA3MTU5NzgzMn0.h1GsXQzezYOA_HZ2occj8c9G4pEOWyNXb50zHRMMLBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});