// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Export a top-level binding so ESM analysis works; initialize below.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export let supabase: any;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
} else {
  // Create a tolerant proxy that delays throwing until a method is actually used.
  const missingMsg = 'Missing Supabase environment variables. Supabase client is unavailable.';

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  function createMissingProxy(): any {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const handler: ProxyHandler<any> = {
      get(_target, prop) {
        if (prop === Symbol.toStringTag) return 'MissingSupabaseClient';
        // return another proxy so chained property access doesn't throw
        return createMissingProxy();
      },
      apply() {
        // When the chain is finally invoked as a function, return a safe resolved promise
        return Promise.resolve({ data: null, error: null });
      },
      construct() {
        return createMissingProxy();
      }
    };

    // function-style proxy so it can be called or have properties accessed
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const fn = (..._args: any[]) => Promise.resolve({ data: null, error: null });
    return new Proxy(fn, handler);
  }

  supabase = createMissingProxy();

  // Helpful warning in console for developers
  // eslint-disable-next-line no-console
  console.warn('Supabase client not initialized: VITE_SUPABASE_URL and/or VITE_SUPABASE_ANON_KEY are missing.');
}